<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Felipe Barreiros - Programador FullStack</title>
        <meta name="viewport" content="width=device-width">
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="/site/css/default.css" rel='stylesheet' type='text/css'>
        <link href="/site/js/vertical-timeline/css/style.css" rel='stylesheet' type='text/css'>

        <script type="text/javascript" src="/site/js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="/site/js/vertical-timeline/js/modernizr.js"></script>
        <script type="text/javascript" src="/site/js/parallax.js-1.4.2/parallax.min.js"></script>
        <script type="text/javascript" src="/site/js/jquery-circle-progress-1.2.1/dist/circle-progress.min.js"></script>
        <script type="text/javascript" src="/site/js/vertical-timeline/js/main.js"></script>
        <script type="text/javascript" src="/site/js/script.js"></script>
    </head>
    <body>
        <div id="menu">
            <div class="inside">
                <div id="photo">
                    <img src="/site/media/images/felipebarreiros.jpg">
                    <span>Felipe Barreiros</span>
                </div>
                <div class="itens">
                    <a class="anchor-scroll" href="#init">início</a>
                    <a class="anchor-scroll" href="#about">sobre mim</a>
                    <a class="anchor-scroll" href="#xp">conhecimento</a>
                    <a class="anchor-scroll" href="#history">histórico profissional</a>
                    <a class="anchor-scroll" href="#contact">contato</a>
                </div>
            </div>
        </div>

        <div id="init" class="container parallax-window" data-parallax="scroll" data-image-src="/site/media/images/fe.jpg" style="padding-top: 100px;">
            <div id="photo_bg"></div>
            <div id="particles-js"></div>
            <div id="absolute-center">
                <div class="info">
                    <a href="#contact" class="cv_impressor anchor-scroll">Download CV</a>
                    <a href="#about" class="cv_impressor knowme anchor-scroll">conheça-me</a>
                    <div class="headline">
                        <h1>Felipe Barreiros</h1>
                        <h2>desenvolvedor web full stack</h2>
                    </div>
                </div>
            </div>
        </div>

        <div id="about" class="container" >
            <div class="parallax-window" data-parallax="scroll" data-image-src="/site/media/images/dev.jpg">
                <div class="bg"></div>
                <div class="title">Sobre mim</div>
            </div>
            <div class="full">
                <div  class="inside">
                    <?php require('../src/views/about.php') ?>
                </div>
            </div>
        </div>

        <div id="xp" class="container" >
            <div class="parallax-window" data-parallax="scroll" data-image-src="/site/media/images/php.jpg">
                <div class="bg"></div>
                <div class="title">Conhecimento</div>
            </div>
            <div class="full">
                <div  class="inside">
                    <?php require('../src/views/knowledge.php') ?>
                </div>
            </div>
        </div>

        <div id="history" class="container" >
            <div class="parallax-window" data-parallax="scroll" data-image-src="/site/media/images/career.jpg">
                <div class="bg"></div>
                <div class="title">histórico profissional</div>
            </div>
            <div class="full">
                <div  class="inside">
                    <?php require('../src/views/resume.php') ?>
                </div>
            </div>
        </div>

        <div id="contact" class="container" >
<!--            <div class="parallax-window" data-parallax="scroll" data-image-src="/site/media/images/career.jpg">-->
<!--                <div class="bg"></div>-->
<!--                <div class="title">histórico profissional</div>-->
<!--            </div>-->
            <div class="full">
                <div  class="inside">
                    <?php require('../src/views/contact.php') ?>
                </div>
            </div>
            <div class="footer">
                <div style="font-size: 10px;">Desenvolvido por Felipe Barreiros - Todos os Direitos Reservados - ©<?= Date('Y'); ?></div>
            </div>
        </div>

    </body>
</html>
